[package]
name = "codegpt_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
tokio-rustls = "0.21"
thiserror = "1"

[lib]
name = "my_crate"
path = "src/lib.rs"